name: Keep Bokrah Backend Awake

on:
  schedule:
    - cron: '*/5 * * * *'       
    - cron: '13/15 * * * *'     
  workflow_dispatch:            

concurrency:
  group: keep-bokrah-awake
  cancel-in-progress: true      

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Bokrah backend
        env:
          URL: ${{ secrets.RENDER_PING_URL }}
        run: |
          echo "::group::Ping"
          echo "Pinging $URL at $(date -u)"
          for i in {1..3}; do
            if curl -sSL "$URL"; then
              echo "Ping succeeded"
              break
            else
              echo "Retry $i failed – sleeping 5s"
              sleep 5
            fi
          done || echo "Ping failed after 3 attempts"
          echo "::endgroup::"
